---
# This is the directory where the openshift-install file is located
# The install-files-directory will be passed to the installer
# and will contain the resulting ignition files and base64 conversions
ocp4_client_directory: "/home/presutti/bin"
ocp4_client_installer_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.3.9/openshift-client-linux-4.3.9.tar.gz"
ocp4_client_archive_name: "{{ ocp4_client_installer_url | basename }}"
ocp4_client_sha_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.3.9/sha256sum.txt"

ocp4_installer_directory: "/home/presutti/ocp"
ocp4_installer_filename: "openshift-install"
ocp4_install_config_name: "install-config.yaml"
ocp4_install_files_directory: "{{ ocp4_installer_directory }}/data"
ocp4_installer_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.3.9/openshift-install-linux-4.3.9.tar.gz"
ocp4_installer_archive_name: "{{ ocp4_installer_url | basename }}"
ocp4_installer_sha_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.3.9/sha256sum.txt"

# RHCOS OVA image
rhcos_ova_url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.3/4.3.8/rhcos-4.3.8-x86_64-vmware.x86_64.ova"
rhcos_ova_archive_name: "{{ rhcos_ova_url | basename }}"
rhcos_ova_sha_url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.3/4.3.8/sha256sum.txt"

# Purely cosmetic
ocp4_major_minor_version: "4.3"

# Some combined variable names to make the later tasks easier to write :)
ocp4_client_file_fullarchivename: "{{ ocp4_installer_directory }}/{{ ocp4_client_archive_name }}"
ocp4_install_file_fullname: "{{ ocp4_install_files_directory }}/{{ ocp4_install_config_name}}"
ocp4_installer_file_fullarchivename: "{{ ocp4_installer_directory }}/{{ ocp4_installer_archive_name }}"
rhcos_ova_file_fullname: "{{ ocp4_installer_directory }}/{{ rhcos_ova_archive_name }}"

# Cluster Variables
base_domain: "internal.yourdomain.com"
cluster_name: ocp4

vsphere_server: "vcenter.internal.yourdomain.com"
vsphere_username: "administrator@internal.yourdomain.com"
vsphere_password: "test123"
vsphere_datacenter: "datacenter"
vsphere_datastore: "datastore"
vsphere_cluster: ""
vsphere_esxi_hostname: ""
vsphere_use_cluster: False
vsphere_use_esxi_hostname: False
ocp_cluster_folder: "ocp4"
rhcos_template_name: "RHCOS"
rhcos_template_vm_network: "VM Network"

# Memory Locking - Lock all VM memory (Not required on OCP 4.3)
vsphere_lock_memory: False
# Latency Sensitivity - Options are "High" and "Normal", with Normal being the default (Not required on OCP 4.3)
vsphere_latency_sensitivity: "Normal"

# SDN Type - Can be OVNKubernetes or OpenShiftSDN
openshift_sdn_type: "OpenShiftSDN"

# Template overrides
template_install_config: "install-config.yml.j2"
template_append_bootstrap: "append-bootstrap.j2"

# Options are "thin, thick, eagerzeroedthick"
vmware_master_disk_provisioning: "thin"
vmware_worker_disk_provisioning: "thin"

# Pull secret is obtained from try.openshift.com
pull_secret: '{"auths": ...}'

# Provide an SSH public key for installation onto the nodes. Username is
# Core for CoreOS nodes.
ssh_key: 'ssh-ed25519 AAAA...'

# Web Server URL (for hosting the bootstrap.ign)
bootstrap_url: "https://webserver.internal.yourdomain.com/ocp/bootstrap.ign"

# Node creation defaults
master_node_memory_mb: 24576
master_node_num_cpus: 4
master_node_num_cpu_cores_per_socket: 4

worker_node_memory_mb: 32768
worker_node_num_cpus: 8
worker_node_num_cpu_cores_per_socket: 4

node_master_disk_size_in_gb: 50
node_master_add_extra_disk: True
node_master_extra_disk_size_in_gb: 100

node_worker_disk_size_in_gb: 50
node_worker_add_extra_disk: True
node_worker_extra_disk_size_in_gb: 100

vmware_guest_os_id: "rhel7_64Guest"
vmware_guest_hardware_version: 14

# Cluster node counts - Will be overwritten based on inventory
cluster_master_replicas: 3
cluster_worker_replicas: 0
